# stages:
#   - build
#   - deploy

# variables:
#   AWS_ACCOUNT_ID: $AWS_ACCOUNT_ID
#   PROJECT_NAME: $PROJECT_NAME
#   ECS_CLUSTER_NAME: $ECS_CLUSTER_NAME
#   FRONTEND_SERVICE_NAME: $FRONTEND_SERVICE_NAME
#   BACKEND_SERVICE_NAME: $BACKEND_SERVICE_NAME
#   AWS_REGION: $AWS_REGION # Your AWS region
#   FRONTEND_IMAGE_TAG: "${AWS_ACCOUNT_ID}.dkr.ecr.${AWS_REGION}.amazonaws.com/${PROJECT_NAME}-web-app:${CI_COMMIT_TAG:-latest}"
#   BACKEND_IMAGE_TAG: "${AWS_ACCOUNT_ID}.dkr.ecr.${AWS_REGION}.amazonaws.com/${PROJECT_NAME}-server:${CI_COMMIT_TAG:-latest}"

# # Build and Push Frontend Image
# build-frontend:
#   stage: build
#   script:
#     - aws ecr get-login-password --region ${AWS_REGION} | docker login --username AWS --password-stdin ${AWS_ACCOUNT_ID}.dkr.ecr.${AWS_REGION}.amazonaws.com
#     - docker build -t ${FRONTEND_IMAGE_TAG} -f client/web-app.Dockerfile ./client
#     - docker push ${FRONTEND_IMAGE_TAG}
#   rules:
#     - changes:
#         - client/**

# # Build and Push Backend Image
# build-backend:
#   stage: build
#   script:
#     - aws ecr get-login-password --region ${AWS_REGION} | docker login --username AWS --password-stdin ${AWS_ACCOUNT_ID}.dkr.ecr.${AWS_REGION}.amazonaws.com
#     - docker build -t ${BACKEND_IMAGE_TAG} -f server/server.Dockerfile ./server
#     - docker push ${BACKEND_IMAGE_TAG}
#   rules:
#     - changes:
#         - server/**

# # Deploy Frontend to ECS
# deploy-frontend:
#   stage: deploy
#   script:
#     - aws ecs update-service \
#         --cluster ${ECS_CLUSTER_NAME} \
#         --service ${FRONTEND_SERVICE_NAME} \
#         --force-new-deployment
#   environment:
#     name: staging
#   rules:
#     - changes:
#         - client/**

# # Deploy Backend to ECS
# deploy-backend:
#   stage: deploy
#   script:
#     - aws ecs update-service \
#         --cluster ${ECS_CLUSTER_NAME} \
#         --service ${BACKEND_SERVICE_NAME} \
#         --force-new-deployment
#   environment:
#     name: staging
#   rules:
#     - changes:
#         - server/**