#Too setup the script, run: chmod +x set-env-vars.sh and then run source set-env-vars.sh
#!/bin/bash

export TF_VAR_EC2_INSTANCE_NAME=$EC2_INSTANCE_NAME
export TF_VAR_EC2_INSTANCE_TYPE=$EC2_INSTANCE_TYPE
export TF_VAR_EC2_INSTANCE_AMI=$EC2_INSTANCE_AMI
export TF_VAR_CIDR_VPC=$CIDR_VPC
export TF_VAR_CIDR_SUBNET=$CIDR_SUBNET
export TF_VAR_CIDR_GATEWAY=$CIDR_GATEWAY
export TF_VAR_CIDR_ROUTE_TABLE=$CIDR_ROUTE_TABLE
export TF_VAR_SECURITY_GROUP_NAME=$SECURITY_GROUP_NAME
export TF_VAR_SECURITY_GROUP_DESCRIPTION=$SECURITY_GROUP_DESCRIPTION
export TF_VAR_ALLOW_HTTP=$ALLOW_HTTP
export TF_VAR_ALLOW_HTTPS=$ALLOW_HTTPS
export TF_VAR_ALLOW_SSH=$ALLOW_SSH
export TF_VAR_PROJECT_NAME=$PROJECT_NAME
export TF_VAR_REPO_URL=$REPO_URL
export TF_VAR_BRANCH_NAME=$BRANCH_NAME
export TF_VAR_GITLAB_PRIVATE_KEY=$GITLAB_PRIVATE_KEY
export TF_VAR_GITLAB_PUBLIC_KEY=$GITLAB_PUBLIC_KEY
export TF_VAR_GITLAB_SSH=$GITLAB_SSH
export TF_VAR_SSH_EC2=$SSH_EC2
export TF_VAR_NGINX_SERVER_PORT=$NGINX_SERVER_PORT
export TF_VAR_REGION=$REGION
export VAULT_ADDR=$VAULT_ADDR

set -a  
source .env
set +a