version: "3.9"

services:
  web-app:
    image: ${PROJECT_NAME}-web-app:${IMAGE_TAG} # Use prebuilt image for staging
    ports:
      - "8000:8000" # Expose the application port
    environment:
      - SERVER_URL=${SERVER_URL} # Staging server URL
    networks:
      - app-network

  server:
    image: ${PROJECT_NAME}-server:${IMAGE_TAG} # Use prebuilt image for staging
    ports:
      - "8080:8080" # Expose the application port
    environment:
      - NODE_ENV=staging # Explicitly set staging environment
    networks:
      - app-network

networks:
  app-network:
    driver: bridge